# Generated by Django 5.0.1 on 2026-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Website', max_length=200)),
                ('welcome_message', models.TextField(default='Welcome to our site!')),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex code like #ffffff', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
