# Generated by Django 5.0.1 on 2026-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_and_backgrounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(choices=[('parts', 'Parts & Components'), ('consumables', 'Consumables'), ('accessories', 'Accessories'), ('tooling', 'Tooling')], default='parts', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_gbp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='machineproduct',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RenameField(
            model_name='backgroundimage',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='machineproduct',
            old_name='button_url',
            new_name='external_link',
        ),
        migrations.RenameField(
            model_name='machineproduct',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='machineproduct',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='backgroundimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='backgroundimage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='machineproduct',
            name='button_text',
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='spec_pdf',
            field=models.FileField(blank=True, null=True, upload_to='spec_sheets/'),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='tagline',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
