# Generated by Django 5.0.1 on 2026-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopproduct_delete_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Main site logo (recommended: PNG with transparent background)', null=True, upload_to='site/')),
                ('hero_title', models.CharField(default='MPE i6', help_text="Main hero heading (e.g., 'MPE i6')", max_length=100)),
                ('hero_subtitle', models.CharField(default='Inline tray Sealer', help_text="Hero subheading (e.g., 'Inline tray Sealer')", max_length=150)),
                ('hero_description', models.TextField(default='High-speed inline tray sealer. Electric operation for maximum produce.', help_text='Hero description text')),
                ('hero_image', models.ImageField(blank=True, help_text='Large hero/showcase machine image', null=True, upload_to='hero/')),
                ('hero_button_text', models.CharField(default='VIEW MACHINES', help_text='Text for the hero call-to-action button', max_length=50)),
                ('hero_button_link', models.CharField(default='#machines', help_text="Link for the hero button (e.g., '#machines' or '/shop/')", max_length=200)),
                ('feature_1', models.CharField(blank=True, default='UK manufacturing', max_length=100)),
                ('feature_2', models.CharField(blank=True, default='Service support', max_length=100)),
                ('feature_3', models.CharField(blank=True, default='Custom automation', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='+44 1663 732700', max_length=50)),
                ('email', models.EmailField(blank=True, default='sales@mpe-uk.com', max_length=254)),
                ('location', models.CharField(blank=True, default='Derbyshire, UK', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
