# Generated by ChatGPT patch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteconfiguration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("category", models.CharField(choices=[("general", "General"), ("forms", "Forms"), ("service", "Service"), ("qa", "QA / ISO"), ("hr", "HR")], default="general", max_length=20)),
                ("file", models.FileField(upload_to="staff_docs/")),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerMachine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140)),
                ("machine_type", models.CharField(choices=[("tray_sealer", "Tray Sealer"), ("sandwich", "Sandwich Sealer"), ("tooling", "Tooling / Spares"), ("other", "Other")], default="tray_sealer", max_length=30)),
                ("serial_number", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_machines", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["customer", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("category", models.CharField(choices=[("general", "General"), ("manuals", "Manuals"), ("spec", "Specification"), ("service", "Service"), ("reports", "Reports")], default="general", max_length=20)),
                ("file", models.FileField(upload_to="customer_docs/")),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_documents", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MachineMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_key", models.CharField(max_length=80)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("timestamp", models.DateTimeField()),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="core.customermachine")),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="machinemetric",
            index=models.Index(fields=["machine", "metric_key", "timestamp"], name="core_metric_mmkt_ts_idx"),
        ),
    ]
