# Generated by Django 5.0.1 on 2026-01-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_portal_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='machinemetric',
            new_name='core_machin_machine_7921d9_idx',
            old_name='core_metric_mmkt_ts_idx',
        ),
    ]
