# Generated by Django 5.0.1 on 2026-01-25 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_0005_hero_slide_0006_rename_core_metric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdocument',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='machinemetric',
            name='machine',
        ),
        migrations.DeleteModel(
            name='StaffDocument',
        ),
        migrations.AlterModelOptions(
            name='customermachine',
            options={},
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_button_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='customermachine',
            name='batch_count',
            field=models.IntegerField(default=0, help_text='Current batch total'),
        ),
        migrations.AddField(
            model_name='customermachine',
            name='efficiency',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='OEE %', max_digits=5),
        ),
        migrations.AddField(
            model_name='customermachine',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customermachine',
            name='production_speed',
            field=models.IntegerField(default=0, help_text='Packs per minute'),
        ),
        migrations.AddField(
            model_name='customermachine',
            name='stoppages',
            field=models.IntegerField(default=0, help_text='Number of stops this shift'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='style',
            field=models.CharField(choices=[('standard', 'Standard Hero'), ('machine', 'Machine Feature'), ('news', 'Latest News')], default='standard', help_text="Choose 'Machine' or 'News' to adjust the layout.", max_length=20),
        ),
        migrations.AlterField(
            model_name='customermachine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customermachine',
            name='name',
            field=models.CharField(help_text='Machine Name/Model (e.g. MPE i6)', max_length=120),
        ),
        migrations.AlterField(
            model_name='customermachine',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('embed', 'Embedded Video (URL)')], default='image', max_length=12),
        ),
        migrations.DeleteModel(
            name='CustomerDocument',
        ),
        migrations.DeleteModel(
            name='MachineMetric',
        ),
    ]
