# Generated by Django 5.0.1 on 2026-01-25 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0008_customerprofile_0008_remove_customerdocument_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('general', 'General'), ('forms', 'Forms'), ('service', 'Service'), ('qa', 'QA / ISO'), ('hr', 'HR')], default='general', max_length=20)),
                ('file', models.FileField(upload_to='staff_docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customermachine',
            options={'ordering': ['customer', 'name']},
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='batch_count',
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='production_speed',
        ),
        migrations.RemoveField(
            model_name='customermachine',
            name='stoppages',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='style',
        ),
        migrations.AddField(
            model_name='customermachine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customermachine',
            name='machine_type',
            field=models.CharField(choices=[('tray_sealer', 'Tray Sealer'), ('sandwich', 'Sandwich Sealer'), ('tooling', 'Tooling / Spares'), ('other', 'Other')], default='tray_sealer', max_length=30),
        ),
        migrations.AddField(
            model_name='customermachine',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_button_link',
            field=models.CharField(default='#machines', help_text='Hero button link', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_button_text',
            field=models.CharField(default='VIEW MACHINES', help_text='Hero button text', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_description',
            field=models.TextField(default='High-speed inline tray sealer. Electric operation for maximum produce.', help_text='Hero description text'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Large hero/showcase machine image', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.CharField(default='Inline tray Sealer', help_text='Hero subheading', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='MPE i6', help_text='Main hero heading', max_length=100),
        ),
        migrations.AlterField(
            model_name='customermachine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customermachine',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='customermachine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('embed', 'Embedded video (URL)')], default='image', max_length=12),
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('general', 'General'), ('manuals', 'Manuals'), ('spec', 'Specification'), ('service', 'Service'), ('reports', 'Reports')], default='general', max_length=20)),
                ('file', models.FileField(upload_to='customer_docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=80)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.customermachine')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', 'metric_key', 'timestamp'], name='core_metric_mmkt_ts_idx')],
            },
        ),
    ]
