# Generated by Django 5.0.1 on 2026-01-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_machinetelemetry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customermachine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffdocument',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='machinemetric',
            name='core_metric_mmkt_ts_idx',
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='category',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='customermachine',
            name='machine_type',
            field=models.CharField(default='tray_sealer', max_length=30),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_link',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(choices=[('parts', 'Parts'), ('consumables', 'Consumables'), ('accessories', 'Accessories'), ('tooling', 'Tooling')], default='parts', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_button_link',
            field=models.CharField(default='#machines', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_button_text',
            field=models.CharField(default='VIEW MACHINES', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_description',
            field=models.TextField(default='High-speed inline tray sealer.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.CharField(default='Inline tray Sealer', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='MPE i6', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='category',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
