# Generated by Django 5.0.1 on 2026-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customerdocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='body',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='bullet_1',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='bullet_2',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='bullet_3',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_button_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True, help_text='Paragraph text'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='show_features',
            field=models.BooleanField(default=True, help_text='Show the standard feature chips (UK Made, etc)?'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='style',
            field=models.CharField(choices=[('machine', 'Machine Showcase'), ('news', 'News / Update')], default='machine', max_length=20),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='Optional: Upload MP4 video (overrides image)', null=True, upload_to='hero_videos/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_link',
            field=models.CharField(blank=True, help_text='Internal path (e.g. /shop/) or full URL', max_length=240),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text',
            field=models.CharField(blank=True, default='View Details', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image', null=True, upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Tagline or short subtitle', max_length=180),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(help_text='Main heading or Machine Name', max_length=120),
        ),
    ]
