# Generated by Django 5.0.1 on 2026-01-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_heroslide_body_remove_heroslide_bullet_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='card_background',
            field=models.ImageField(blank=True, help_text='Optional: Replace the dark box behind the machine with an image.', null=True, upload_to='hero_bgs/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='transparent_background',
            field=models.BooleanField(default=False, help_text='Check this to remove the dark background box completely.'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_link',
            field=models.CharField(blank=True, help_text='Internal path or full URL', max_length=240),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='show_features',
            field=models.BooleanField(default=True, help_text='Show the standard feature chips?'),
        ),
    ]
