# Generated by Django 5.0.1 on 2026-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_heroslide_card_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text='e.g. United Kingdom', max_length=100)),
                ('flag_code', models.CharField(help_text="ISO 2-letter code (e.g. 'gb', 'us', 'ca')", max_length=5)),
                ('description', models.TextField(help_text="Short text, e.g. 'Sales & Support partner'")),
                ('cta_text', models.CharField(default='Contact Us', help_text='Button label', max_length=50)),
                ('cta_link', models.CharField(help_text='URL or mailto: link', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
