# Generated by ChatGPT patch: admin-configurable theme/nav/logo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_distributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_light",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_dark",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="default_theme",
            field=models.CharField(choices=[("light", "Light"), ("dark", "Dark"), ("auto", "Auto (system)")], default="light", max_length=10),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="show_theme_toggle",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="animate_buttons",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bg_light",
            field=models.CharField(default="#f6f7f8", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bg_dark",
            field=models.CharField(default="#0f1115", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="surface_light",
            field=models.CharField(default="#ffffff", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="surface_dark",
            field=models.CharField(default="#171a21", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="accent",
            field=models.CharField(default="#2f7d32", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="accent_2",
            field=models.CharField(default="#1f5f24", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_bg_light",
            field=models.CharField(default="#ffffff", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_bg_dark",
            field=models.CharField(default="#141824", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_border_light",
            field=models.CharField(default="#e5e7eb", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_border_dark",
            field=models.CharField(default="#252b3a", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_link_light",
            field=models.CharField(default="#111827", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_link_dark",
            field=models.CharField(default="#e5e7eb", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_link_hover",
            field=models.CharField(default="#2f7d32", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_link_active",
            field=models.CharField(default="#2f7d32", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_item_colours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="btn_primary",
            field=models.CharField(default="#2f7d32", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="btn_secondary",
            field=models.CharField(default="#2563eb", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="btn_warning",
            field=models.CharField(default="#f59e0b", max_length=20),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="btn_danger",
            field=models.CharField(default="#dc2626", max_length=20),
        ),
    ]
