# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_distributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_bg_color",
            field=models.CharField(blank=True, default="#1f9d55", help_text="Nav button background colour (hex).", max_length=9),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_bg_opacity",
            field=models.FloatField(blank=True, default=0.14, help_text="Nav button background opacity (0.0 to 1.0)."),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_text_color",
            field=models.CharField(blank=True, default="#0f172a", help_text="Nav button text colour (hex).", max_length=9),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_border_color",
            field=models.CharField(blank=True, default="#1f9d55", help_text="Nav button border colour (hex).", max_length=9),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_border_opacity",
            field=models.FloatField(blank=True, default=0.25, help_text="Nav button border opacity (0.0 to 1.0)."),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_bg_hover_color",
            field=models.CharField(blank=True, default="#1f9d55", help_text="Nav button hover background colour (hex).", max_length=9),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_bg_hover_opacity",
            field=models.FloatField(blank=True, default=0.22, help_text="Nav button hover background opacity (0.0 to 1.0)."),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_text_hover_color",
            field=models.CharField(blank=True, default="#0b1220", help_text="Nav button hover text colour (hex).", max_length=9),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_border_hover_color",
            field=models.CharField(blank=True, default="#1f9d55", help_text="Nav button hover border colour (hex).", max_length=9),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_border_hover_opacity",
            field=models.FloatField(blank=True, default=0.38, help_text="Nav button hover border opacity (0.0 to 1.0)."),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_btn_text_shadow",
            field=models.CharField(blank=True, default="0 1px 2px rgba(0,0,0,.25)", help_text="CSS text-shadow used on nav links to improve readability (optional).", max_length=80),
        ),
    ]
