# Generated by ChatGPT to resolve parallel 0016 migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_site_theme_fields"),
        ("core", "0016_site_theme_navbar"),
    ]

    operations = []
