# Generated by Django 5.0.1 on 2026-01-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_siteconfig_nav_theme'),
        ('core', '0017_merge_0016_site_theme_fields_0016_site_theme_navbar'),
    ]

    operations = [
    ]
