# Generated by Django 5.0.1 on 2026-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260129_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='accent',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='accent_2',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='animate_buttons',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='bg_dark',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='bg_light',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='btn_danger',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='btn_primary',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='btn_secondary',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='btn_warning',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='default_theme',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='logo_dark',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='logo_light',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_bg_dark',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_bg_light',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_border_dark',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_border_light',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_item_colours',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_link_active',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_link_dark',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_link_hover',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='nav_link_light',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='show_theme_toggle',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='surface_dark',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='surface_light',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_bg_color',
            field=models.CharField(blank=True, default='#1f9d55', help_text='Nav button background (hex)', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_bg_hover_color',
            field=models.CharField(blank=True, default='#1f9d55', help_text='Nav button hover background (hex)', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_bg_hover_opacity',
            field=models.PositiveSmallIntegerField(default=22, help_text='0-100 (%)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_bg_opacity',
            field=models.PositiveSmallIntegerField(default=14, help_text='0-100 (%)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_border_color',
            field=models.CharField(blank=True, default='#1f9d55', help_text='Nav button border colour (hex)', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_border_hover_color',
            field=models.CharField(blank=True, default='#1f9d55', help_text='Nav button hover border (hex)', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_border_hover_opacity',
            field=models.PositiveSmallIntegerField(default=38, help_text='0-100 (%)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_border_opacity',
            field=models.PositiveSmallIntegerField(default=25, help_text='0-100 (%)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_text_color',
            field=models.CharField(blank=True, default='#0f172a', help_text='Nav button text colour (hex)', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_text_hover_color',
            field=models.CharField(blank=True, default='#0b1220', help_text='Nav button hover text colour (hex)', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_text_shadow',
            field=models.CharField(blank=True, default='0 1px 2px rgba(0,0,0,.25)', help_text='CSS text-shadow for readability', max_length=64),
        ),
    ]
