# Generated by Django 5.0.1 on 2026-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_siteconfiguration_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Small icon for browser tab', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_bg_color',
            field=models.CharField(default='#0f172a', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_link_color',
            field=models.CharField(default='#1f9d55', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_text_color',
            field=models.CharField(default='#0f172a', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='link_color',
            field=models.CharField(default='#1f9d55', help_text='Hyperlink text color', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(default='#1f9d55', help_text='Primary Brand Color (Buttons, Highlights)', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(default='#0f172a', help_text='Secondary Brand Color (Dark backgrounds)', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_bg_color',
            field=models.CharField(default='#ffffff', help_text='Main page background color', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_bg_image',
            field=models.ImageField(blank=True, help_text='Optional: Overrides background color', null=True, upload_to='site/theme/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_text_color',
            field=models.CharField(default='#333333', help_text='Main body text color', max_length=32),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='cta_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='cta_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='flag_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='card_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero_bgs/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_link',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='show_features',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='transparent_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_bg_color',
            field=models.CharField(blank=True, default='#1f9d55', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_bg_hover_color',
            field=models.CharField(blank=True, default='#1f9d55', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_border_color',
            field=models.CharField(blank=True, default='#1f9d55', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_border_hover_color',
            field=models.CharField(blank=True, default='#1f9d55', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_text_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_text_hover_color',
            field=models.CharField(blank=True, default='#0b1220', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nav_btn_text_shadow',
            field=models.CharField(blank=True, default='0 1px 2px rgba(0,0,0,.25)', max_length=64),
        ),
    ]
