# Generated by Django 5.0.1 on 2026-01-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_siteconfiguration_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='card_bg_color',
            field=models.CharField(default='#ffffff', help_text='Background for boxes/cards', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='card_text_color',
            field=models.CharField(default='#333333', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_bg_color',
            field=models.CharField(default='#001a4d', help_text='Hero/Banner background color', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_text_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='section_alt_bg_color',
            field=models.CharField(default='#f3f4f6', help_text='Background for alternating sections (stripes)', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='topbar_bg_color',
            field=models.CharField(default='#ffffff', help_text='Very top strip background', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='topbar_text_color',
            field=models.CharField(default='#333333', max_length=32),
        ),
    ]
