# Generated by Django 5.0.1 on 2026-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_siteconfiguration_card_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Full screen background image (e.g. oranges/factory)', null=True, upload_to='hero_bgs_full/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='bg_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=50, help_text='Darkness of the overlay (0-100%). Higher = darker background.'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='bg_video',
            field=models.FileField(blank=True, help_text='Full screen background video (MP4)', null=True, upload_to='hero_bg_videos/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='card_background',
            field=models.ImageField(blank=True, help_text='Optional: Texture for the specific content box.', null=True, upload_to='hero_bgs/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_link',
            field=models.CharField(blank=True, help_text='Internal path or full URL', max_length=240),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True, help_text='Paragraph text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Foreground image (machine cutout)', null=True, upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='show_features',
            field=models.BooleanField(default=True, help_text='Show the standard feature chips?'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Tagline or short subtitle', max_length=180),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='transparent_background',
            field=models.BooleanField(default=False, help_text="Check this to make the content box transparent (good for 'See More' style slides)."),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='Foreground video (machine running)', null=True, upload_to='hero_videos/'),
        ),
    ]
