# Generated by Django 5.0.1 on 2026-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_heroslide_bg_image_heroslide_bg_overlay_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_box_bg_color',
            field=models.CharField(default='#001a4d', help_text='Background color of the text box over the image', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_box_bg_opacity',
            field=models.PositiveSmallIntegerField(default=85, help_text='0-100% (0 is transparent, 100 is solid)'),
        ),
    ]
