# Generated by Django 5.0.1 on 2026-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_siteconfiguration_hero_box_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Optional: Solid background color if no image/video is uploaded.', max_length=32),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Full screen background image', null=True, upload_to='hero_bgs_full/'),
        ),
    ]
