# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_heroslide_bg_color_alter_heroslide_bg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_dots_enabled",
            field=models.BooleanField(default=True, help_text="Show the hero slide indicator dots."),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_dots_bottom_offset",
            field=models.PositiveSmallIntegerField(
                default=24, help_text="Distance in pixels from the bottom of the hero banner to place the dots."
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_dots_color",
            field=models.CharField(
                default="#ffffff", help_text="Dot colour (hex), e.g. #ffffff.", max_length=7
            ),
        ),
    ]
