# Generated by ChatGPT patch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_heroslide_bg_color_alter_heroslide_bg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="machines_section_bg_color",
            field=models.CharField(default="#f3f4f6", help_text="Background for the 'Our Machinery Range' section", max_length=32),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="machines_section_text_color",
            field=models.CharField(default="#0b1220", help_text="Text color for the 'Our Machinery Range' section", max_length=32),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="distributors_section_bg_color",
            field=models.CharField(default="#0b1220", help_text="Background for the 'Global Distribution Network' section", max_length=32),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="distributors_section_text_color",
            field=models.CharField(default="#ffffff", help_text="Text color for the 'Global Distribution Network' section", max_length=32),
        ),
    ]
