# Generated by Django 5.0.1 on 2026-01-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_siteconfiguration_hero_dots'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='hero_dots_bottom_offset',
            field=models.PositiveSmallIntegerField(default=24, help_text='Distance in pixels from the bottom of the hero banner to place the dots.'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='hero_dots_color',
            field=models.CharField(default='#ffffff', help_text='Dot colour (hex), e.g. #ffffff.', max_length=7),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='hero_dots_enabled',
            field=models.BooleanField(default=True, help_text='Show the hero slide indicator dots.'),
        ),
    ]
