# Generated by Django 5.0.1 on 2026-01-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_section_specific_colors'),
        ('core', '0026_heroslide_hero_dots_bottom_offset_and_more'),
    ]

    operations = [
    ]
