# Generated by Django 5.0.1 on 2026-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_styleoverride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='hero_dots_bottom_offset',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='hero_dots_color',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='hero_dots_enabled',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_dots_bottom_offset',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_dots_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_dots_enabled',
        ),
        migrations.AddField(
            model_name='distributor',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Optional background color', max_length=32),
        ),
        migrations.AddField(
            model_name='distributor',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo to replace flag', null=True, upload_to='distributors/'),
        ),
        migrations.AlterField(
            model_name='styleoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
