# Generated by Django 5.0.1 on 2026-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_heroslide_hero_dots_bottom_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Global custom CSS applied to the whole site.'),
        ),
    ]
