# Generated by Django 5.0.1 on 2026-01-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_siteconfiguration_custom_css'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StyleOverride',
        ),
    ]
