# Generated by Django 5.0.1 on 2026-01-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_styleoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='text_color',
            field=models.CharField(blank=True, help_text='Optional text color', max_length=32),
        ),
    ]
