# Generated by Django 5.0.1 on 2026-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_distributor_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='description_color',
            field=models.CharField(blank=True, help_text='Optional description text color', max_length=32),
        ),
    ]
