# Generated by Django 5.0.1 on 2026-01-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_distributor_description_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_hero_bg_color',
            field=models.CharField(default='#001a4d', help_text='Contact page hero background', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_hero_text_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_section_bg_color',
            field=models.CharField(default='#f3f4f6', help_text='Contact page main section background', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_section_text_color',
            field=models.CharField(default='#333333', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_hero_bg_color',
            field=models.CharField(default='#001a4d', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_hero_text_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_section_bg_color',
            field=models.CharField(default='#f3f4f6', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='documents_section_text_color',
            field=models.CharField(default='#333333', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='portal_hero_bg_color',
            field=models.CharField(default='#001a4d', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='portal_hero_text_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='portal_section_bg_color',
            field=models.CharField(default='#f3f4f6', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='portal_section_text_color',
            field=models.CharField(default='#333333', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='shop_hero_bg_color',
            field=models.CharField(default='#001a4d', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='shop_hero_text_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='shop_section_bg_color',
            field=models.CharField(default='#f3f4f6', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='shop_section_text_color',
            field=models.CharField(default='#333333', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tooling_hero_bg_color',
            field=models.CharField(default='#001a4d', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tooling_hero_text_color',
            field=models.CharField(default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tooling_section_bg_color',
            field=models.CharField(default='#f3f4f6', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tooling_section_text_color',
            field=models.CharField(default='#333333', max_length=32),
        ),
    ]
