# Generated by Django 5.0.1 on 2026-01-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_siteconfiguration_contact_hero_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='border_color',
            field=models.CharField(blank=True, help_text='Optional border color', max_length=32),
        ),
    ]
