# Generated by Django 5.0.1 on 2026-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_distributor_border_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='btn_bg_color',
            field=models.CharField(blank=True, help_text='Optional button background color', max_length=32),
        ),
        migrations.AddField(
            model_name='distributor',
            name='btn_text_color',
            field=models.CharField(blank=True, help_text='Optional button text color', max_length=32),
        ),
    ]
