# Generated by Django 5.0.1 on 2026-01-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_distributor_btn_bg_color_distributor_btn_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='tooling_feature_bg_color',
            field=models.CharField(default='#ffffff', help_text='Background color for feature cards', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tooling_feature_text_color',
            field=models.CharField(default='#333333', help_text='Text color for feature cards', max_length=32),
        ),
    ]
