# Generated by Django 5.0.1 on 2026-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_siteconfiguration_tooling_feature_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='tooling_section_heading_color',
            field=models.CharField(default='#333333', help_text='Color for H2 headings', max_length=32),
        ),
    ]
