# Generated by Django 5.0.1 on 2026-01-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_siteconfiguration_tooling_section_heading_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='cta_text',
        ),
    ]
