# Generated by ChatGPT on 2026-02-02
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_remove_distributor_cta_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="shop_show_prices",
            field=models.BooleanField(
                default=True,
                help_text="If disabled, prices are hidden across the shop and customers must request a quote.",
            ),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="show_price",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, the price is hidden for this product.",
            ),
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140)),
                ("company", models.CharField(blank=True, max_length=180)),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["company", "name"]},
        ),
        migrations.CreateModel(
            name="ShopOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(blank=True, help_text="Customer's internal order/reference number", max_length=80)),
                ("status", models.CharField(choices=[("new", "New"), ("processing", "Processing"), ("complete", "Complete")], default="new", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="core.customercontact")),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, help_text="e.g. Delivery, Head Office", max_length=80)),
                ("address_1", models.CharField(max_length=200)),
                ("address_2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("county", models.CharField(blank=True, max_length=120)),
                ("postcode", models.CharField(blank=True, max_length=30)),
                ("country", models.CharField(blank=True, default="United Kingdom", max_length=80)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="core.customercontact")),
            ],
            options={"ordering": ["-is_default", "label", "postcode"]},
        ),
        migrations.CreateModel(
            name="ShopOrderAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, max_length=80)),
                ("address_1", models.CharField(max_length=200)),
                ("address_2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("county", models.CharField(blank=True, max_length=120)),
                ("postcode", models.CharField(blank=True, max_length=30)),
                ("country", models.CharField(blank=True, default="United Kingdom", max_length=80)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="order_addresses", to="core.shoporder")),
            ],
        ),
        migrations.CreateModel(
            name="ShopOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=160)),
                ("sku", models.CharField(blank=True, max_length=60)),
                ("unit_price_gbp", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="core.shoporder")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.shopproduct")),
            ],
        ),
    ]
