# Generated by Django 5.0.1 on 2026-02-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_fix_shopproduct_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoporder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text="Key/value specs shown on the product page (e.g. {'Voltage':'230V','Material':'Stainless'})", null=True),
        ),
    ]
