# Generated by Django 5.0.1 on 2026-02-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_shoporder_options_and_more'),
        ('core', '0046_enforce_shopproduct_slug_unique'),
    ]

    operations = [
    ]
