# Generated by Django 5.0.1 on 2026-02-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('processing', 'Processing'), ('complete', 'Complete')], default='new', max_length=20),
        ),
    ]
