# Generated by ChatGPT patch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_shoporder_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_email", models.EmailField(blank=True, default="sales@mpe-uk.com", max_length=254)),
                ("reply_to_email", models.EmailField(blank=True, default="sales@mpe-uk.com", max_length=254)),
                (
                    "internal_recipients",
                    models.TextField(
                        blank=True,
                        default="sales@mpe-uk.com\nservice@mpe-uk.com\naccounts@mpe-uk.com",
                        help_text="Internal recipients (one per line or comma-separated).",
                    ),
                ),
                ("send_to_customer", models.BooleanField(default=True)),
                ("send_to_internal", models.BooleanField(default=True)),
                ("attach_order_pdf", models.BooleanField(default=True)),
                (
                    "pdf_filename_template",
                    models.CharField(
                        blank=True,
                        default="Order_{order_id}.pdf",
                        help_text="Attachment filename template. Available: {order_id}, {order_number}",
                        max_length=200,
                    ),
                ),
                (
                    "customer_subject_template",
                    models.CharField(
                        blank=True,
                        default="Your order from MPE UK Ltd (Ref {order_ref})",
                        max_length=200,
                    ),
                ),
                (
                    "internal_subject_template",
                    models.CharField(
                        blank=True,
                        default="New website order received (Ref {order_ref})",
                        max_length=200,
                    ),
                ),
                (
                    "footer_note",
                    models.CharField(
                        blank=True,
                        default="MPE UK Ltd | Unit 1, Bowden Lane, Derbyshire, SK23 0DQ | +44 1663 732700",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email configuration",
                "verbose_name_plural": "Email configurations",
            },
        ),
    ]
