# Generated by ChatGPT patch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_shoporder_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_email", models.EmailField(blank=True, default="sales@mpe-uk.com", max_length=254)),
                ("reply_to_email", models.EmailField(blank=True, default="sales@mpe-uk.com", max_length=254)),
                (
                    "internal_recipients",
                    models.TextField(
                        blank=True,
                        default="sales@mpe-uk.com\nservice@mpe-uk.com\naccounts@mpe-uk.com",
                        help_text="One per line (or comma separated). These receive order notifications.",
                    ),
                ),
                ("send_to_customer", models.BooleanField(default=True)),
                ("send_to_internal", models.BooleanField(default=True)),
                ("attach_order_pdf", models.BooleanField(default=True)),
                (
                    "customer_subject",
                    models.CharField(
                        blank=True,
                        default="Your order from MPE UK Ltd (Order {order_ref})",
                        max_length=200,
                    ),
                ),
                (
                    "internal_subject",
                    models.CharField(
                        blank=True,
                        default="New website order received (Order {order_ref})",
                        max_length=200,
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        default="MPE UK Ltd | Unit 1, Bowden Lane, Derbyshire, SK23 0DQ | +44 1663 732700",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email configuration",
                "verbose_name_plural": "Email configurations",
            },
        ),
    ]
