# Generated by Django 5.0.1 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_shoporder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_logo', models.ImageField(blank=True, help_text='Logo used in generated PDFs (e.g. Order Summary).', null=True, upload_to='site/pdf/')),
                ('company_name', models.CharField(blank=True, default='MPE UK Ltd', max_length=100)),
                ('header_email', models.EmailField(blank=True, default='sales@mpe-uk.com', max_length=254)),
                ('header_phone', models.CharField(blank=True, default='+44 1663 732700', max_length=50)),
                ('header_location', models.CharField(blank=True, default='Unit 1, Bowden Lane, Derbyshire, SK23 0DQ', max_length=150)),
                ('document_title', models.CharField(blank=True, default='Order Summary', max_length=60)),
                ('accent_color', models.CharField(blank=True, default='#2E7D32', help_text='Header accent colour (hex), e.g. #2E7D32', max_length=7)),
                ('footer_text', models.CharField(blank=True, default='Generated by MPE Web Site', max_length=200)),
                ('show_page_numbers', models.BooleanField(default=True)),
            ],
        ),
    ]
