# Generated by ChatGPT on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_pdfconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        default="sales@mpe-uk.com",
                        max_length=254,
                        help_text="Default From address used for outgoing emails.",
                    ),
                ),
                (
                    "reply_to_email",
                    models.EmailField(
                        blank=True,
                        default="sales@mpe-uk.com",
                        max_length=254,
                        help_text="Reply-To address (where customer replies should go).",
                    ),
                ),
                (
                    "internal_recipients",
                    models.TextField(
                        blank=True,
                        default="sales@mpe-uk.com",
                        help_text="Comma or newline separated list of MPE recipient emails for order notifications.",
                    ),
                ),
                (
                    "send_customer_email",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, the customer receives an email confirmation with their PDF.",
                    ),
                ),
                (
                    "send_internal_email",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, internal recipients are emailed when an order is placed.",
                    ),
                ),
                (
                    "attach_order_pdf",
                    models.BooleanField(
                        default=True,
                        help_text="Attach the generated Order PDF to outgoing order emails.",
                    ),
                ),
                (
                    "pdf_filename_template",
                    models.CharField(
                        blank=True,
                        default="MPE_Order_{order_id}.pdf",
                        max_length=120,
                        help_text="Filename for the attached PDF. You can use {order_id}.",
                    ),
                ),
            ],
        ),
    ]
