# Generated by ChatGPT on 2026-02-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_emailconfiguration"),
        ("core", "0050_pdfconfiguration"),
    ]

    operations = []
