# Generated by ChatGPT on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_merge_email_pdfconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoporder",
            name="email_sent_to_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shoporder",
            name="email_sent_to_internal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shoporder",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shoporder",
            name="email_last_error",
            field=models.TextField(blank=True),
        ),
    ]
