# Generated by ChatGPT on 2026-02-15
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_shoporder_email_tracking"),
    ]

    operations = [
        # Add slug WITHOUT unique constraint first (Postgres-safe)
        migrations.AddField(
            model_name="machineproduct",
            name="slug",
            field=models.SlugField(max_length=120, null=True, blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="hero_title",
            field=models.CharField(max_length=200, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="hero_subtitle",
            field=models.CharField(max_length=300, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="hero_image",
            field=models.ImageField(upload_to="machine_products/hero/", blank=True, null=True),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="overview",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="key_features",
            field=models.TextField(blank=True, default=""),
        ),

        migrations.CreateModel(
            name="MachineProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="machine_products/gallery/")),
                ("caption", models.CharField(max_length=200, blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery_images", to="core.machineproduct")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),

        migrations.CreateModel(
            name="MachineProductDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="machine_products/docs/", blank=True, null=True)),
                ("external_url", models.URLField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="core.machineproduct")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),

        migrations.CreateModel(
            name="MachineProductVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, blank=True, default="")),
                ("video_url", models.URLField(help_text="YouTube/Vimeo link or any URL", blank=True, default="")),
                ("embed_url", models.URLField(help_text="Optional: paste an embed URL if you have one", blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="videos", to="core.machineproduct")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
    ]
