# Generated by ChatGPT on 2026-02-15

from django.db import migrations, models
import django.db.models.deletion


def populate_machine_slugs(apps, schema_editor):
    MachineProduct = apps.get_model("core", "MachineProduct")
    from django.utils.text import slugify

    for mp in MachineProduct.objects.all().order_by("id"):
        if mp.slug:
            continue
        base = slugify(mp.name)[:150] or "machine"
        slug = base
        i = 2
        while MachineProduct.objects.filter(slug=slug).exclude(pk=mp.pk).exists():
            slug = f"{base}-{i}"
            i += 1
        mp.slug = slug
        mp.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_shoporder_email_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineproduct",
            name="slug",
            # NOTE:
            # We intentionally do NOT add the unique constraint here.
            # Existing rows may initially have an empty/NULL slug, which would
            # cause Postgres to fail when creating the unique index.
            # We populate slugs first, then add the unique constraint in a
            # follow-up migration.
            field=models.SlugField(
                blank=True,
                null=True,
                help_text="SEO-friendly URL slug (auto-generated if blank)",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="machines/hero/"),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="hero_heading",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="hero_subheading",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="overview_title",
            field=models.CharField(blank=True, default="Overview", max_length=140),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="overview_body",
            field=models.TextField(blank=True, help_text="Main body text for the machine page"),
        ),
        migrations.AddField(
            model_name="machineproduct",
            name="key_features",
            field=models.TextField(blank=True, help_text="One feature per line (we will display these as bullet points)"),
        ),
        migrations.CreateModel(
            name="MachineProductDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("file", models.FileField(blank=True, null=True, upload_to="machines/documents/")),
                ("url", models.URLField(blank=True, help_text="Optional external link instead of uploading a file")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.machineproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="MachineProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="machines/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="core.machineproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MachineProductVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=140)),
                ("url", models.URLField(help_text="YouTube/Vimeo or any external video link")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="core.machineproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RunPython(populate_machine_slugs, migrations.RunPython.noop),
    ]
