# Generated by Django 5.0.1 on 2026-02-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_machineproduct_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfconfiguration',
            options={'verbose_name': 'PDF configuration', 'verbose_name_plural': 'PDF configurations'},
        ),
    ]
