# Generated by ChatGPT on 2026-02-15
from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    # We get the model from 'apps' so it matches the database state at this specific time,
    # preventing errors if the model in models.py has fields not yet in the database.
    MachineProduct = apps.get_model("core", "MachineProduct")
    db_alias = schema_editor.connection.alias

    # Build a set of existing slugs to ensure we generate unique ones.
    # This is important because a later migration will make this field unique.
    existing_slugs = set(
        s for s in MachineProduct.objects.using(db_alias).values_list("slug", flat=True).exclude(slug__isnull=True).exclude(slug="")
    )

    # By using .only(), we explicitly fetch only the fields we need.
    # This prevents the "UndefinedColumn" error for fields like 'hero_title'
    # that are not used in this function.
    for mp in MachineProduct.objects.using(db_alias).only("id", "name", "slug").order_by("id"):
        # If slug is already set and valid, skip it.
        if mp.slug and mp.slug in existing_slugs:
            continue

        base_source = mp.name or ""
        base_slug = slugify(base_source)[:110] if base_source else ""

        # Fallback if name is empty or results in an empty slug
        if not base_slug:
            base_slug = f"machine-{mp.id}"

        # Ensure the generated slug is unique
        slug = base_slug
        i = 2
        while slug in existing_slugs:
            slug = f"{base_slug}-{i}"
            i += 1

        mp.slug = slug
        mp.save(using=db_alias, update_fields=["slug"])
        existing_slugs.add(slug)

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_pdfconfiguration_options"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
