# Generated by ChatGPT on 2026-02-15
from django.db import migrations
from django.utils.text import slugify

def populate_unique_slugs(apps, schema_editor):
    MachineProduct = apps.get_model("core", "MachineProduct")
    # Build a set of existing non-empty slugs
    existing = set(
        s for s in MachineProduct.objects.exclude(slug__isnull=True).values_list("slug", flat=True)
        if s
    )

    for mp in MachineProduct.objects.all().order_by("id"):
        # If already set and non-empty, leave it alone
        if getattr(mp, "slug", None):
            continue

        # Prefer 'name' (your model uses name). Fallbacks just in case.
        base_source = getattr(mp, "name", "") or getattr(mp, "title", "") or ""
        base = slugify(base_source)[:110] if base_source else ""
        if not base:
            base = f"machine-{mp.id}"

        slug = base
        i = 2
        while slug in existing:
            slug = f"{base}-{i}"
            i += 1

        mp.slug = slug
        mp.save(update_fields=["slug"])
        existing.add(slug)

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_pdfconfiguration_options"),
    ]

    operations = [
        migrations.RunPython(populate_unique_slugs, migrations.RunPython.noop),
    ]
