# Generated by ChatGPT on 2026-02-15

from django.db import migrations, models


def populate_machine_slugs(apps, schema_editor):
    MachineProduct = apps.get_model("core", "MachineProduct")
    from django.utils.text import slugify

    # Ensure every MachineProduct has a unique, non-empty slug
    for mp in MachineProduct.objects.all().order_by("id"):
        if mp.slug:
            # Normalise any accidental whitespace
            mp.slug = mp.slug.strip()
            if mp.slug:
                mp.save(update_fields=["slug"])
                continue

        base = slugify(mp.name)[:150] or "machine"
        slug = base
        i = 2
        while MachineProduct.objects.filter(slug=slug).exclude(pk=mp.pk).exists():
            slug = f"{base}-{i}"
            i += 1
        mp.slug = slug
        mp.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_pdfconfiguration_options"),
    ]

    operations = [
        migrations.RunPython(populate_machine_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="machineproduct",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO-friendly URL slug (auto-generated if blank)",
                max_length=160,
                unique=True,
            ),
        ),
    ]
