# Generated by ChatGPT on 2026-02-15
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_populate_machineproduct_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineproduct",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="machineproduct",
            name="slug",
            field=models.SlugField(max_length=120, unique=True, null=False),
        ),
    ]
