# Generated by ChatGPT on 2026-02-15
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_populate_machineproduct_slugs"),
    ]

    operations = [
        # The unique constraint this migration tries to create already exists on the production DB.
        # By making this migration do nothing, we can get Django to mark it as applied without error.
        # The original operations were removed to prevent a "DuplicateTable" error on deploy.
    ]
