# Generated by ChatGPT on 2026-02-15
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_make_machineproduct_slug_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineProductStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=32, help_text="e.g. 120, 50+, 24/7")),
                ("label", models.CharField(max_length=80, help_text="e.g. Packs per minute")),
                ("unit", models.CharField(blank=True, max_length=32, help_text="Optional unit, e.g. ppm")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_highlight", models.BooleanField(default=False, help_text="If enabled, this stat may be styled more prominently")),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="core.machineproduct")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="MachineProductFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.CharField(choices=[("speed", "Speed / Throughput"), ("tooling", "Tooling / Changeover"), ("electric", "All-electric / Heat"), ("build", "Industrial build"), ("hygiene", "Hygienic design"), ("support", "Service support"), ("map", "MAP / Gas"), ("custom", "Custom feature")], default="speed", max_length=32)),
                ("title", models.CharField(max_length=60, help_text="Short feature name, e.g. Speed")),
                ("short_text", models.CharField(max_length=120, help_text="e.g. Up to 120 packs/min")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_highlight", models.BooleanField(default=False, help_text="If enabled, this feature may be styled more prominently")),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="core.machineproduct")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
    ]
