# Generated by Django 5.0.1 on 2026-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_machineproduct_stats_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineproductdocument',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.RemoveField(
            model_name='machineproduct',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='machineproductdocument',
            name='external_url',
        ),
        migrations.AddField(
            model_name='machineproduct',
            name='overview_body',
            field=models.TextField(blank=True, help_text='Main body text for the machine page'),
        ),
        migrations.AddField(
            model_name='machineproduct',
            name='overview_title',
            field=models.CharField(blank=True, default='Overview', max_length=140),
        ),
        migrations.AddField(
            model_name='machineproductdocument',
            name='url',
            field=models.URLField(blank=True, help_text='Optional external link instead of uploading a file'),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/hero/'),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='key_features',
            field=models.TextField(blank=True, help_text='One feature per line (we will display these as bullet points)'),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated if blank)', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='machineproductdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='machines/documents/'),
        ),
        migrations.AlterField(
            model_name='machineproductdocument',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='machineproductimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='machineproductimage',
            name='image',
            field=models.ImageField(upload_to='machines/gallery/'),
        ),
        migrations.AlterField(
            model_name='machineproductvideo',
            name='embed_url',
            field=models.URLField(blank=True, default='', help_text='Optional: paste an embed URL (if blank we auto-generate from video_url where possible).'),
        ),
        migrations.AlterField(
            model_name='machineproductvideo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='machineproductvideo',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube/Vimeo (watch link) or any external video URL'),
        ),
    ]
