# Generated by ChatGPT on 2026-02-15
# Purpose: Railway/Postgres DB is missing MachineProduct hero_title/hero_subtitle columns.
# This migration *only* patches the database (no state change), so it is safe even if your local DB already has the columns.

from django.db import migrations

def add_missing_columns(apps, schema_editor):
    vendor = schema_editor.connection.vendor

    # We only need to patch Postgres on Railway. Local dev (SQLite) typically already has the columns after a rebuild.
    if vendor != "postgresql":
        return

    # Add columns if they don't exist (Postgres supports IF NOT EXISTS)
    schema_editor.execute(
        "ALTER TABLE core_machineproduct ADD COLUMN IF NOT EXISTS hero_title varchar(200) NOT NULL DEFAULT '';"
    )
    schema_editor.execute(
        "ALTER TABLE core_machineproduct ADD COLUMN IF NOT EXISTS hero_subtitle varchar(300) NOT NULL DEFAULT '';"
    )

    # To fix the error, get the historical model from the `apps` registry
    # instead of importing it directly from `core.models`.
    MachineProduct = apps.get_model('core', 'MachineProduct')

    # The loop you mentioned will now work correctly.
    for mp in MachineProduct.objects.all().order_by("id"):
        # Add your data population logic here. For example:
        # if not mp.hero_title:
        #     mp.hero_title = mp.name
        #     mp.save(update_fields=['hero_title'])
        pass

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_machineproduct_stats_features"),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, migrations.RunPython.noop),
    ]
