# Generated by Django 5.0.1 on 2026-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_machineproduct_stats_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineproductdocument',
            options={'ordering': ['sort_order', 'title']},
        ),
        # The 'overview' column may have been removed in a previous failed migration.
        # Using RunSQL with 'IF EXISTS' makes this operation idempotent and safe to re-run.
        # The state_operations keeps Django's model state consistent with the schema change.
        migrations.RunSQL(
            sql="ALTER TABLE core_machineproduct DROP COLUMN IF EXISTS overview CASCADE;",
            state_operations=[
                migrations.RemoveField(
                    model_name='machineproduct',
                    name='overview',
                ),
            ]
        ),
        # The 'external_url' column may also have been removed in a previous failed migration.
        # Using RunSQL with 'IF EXISTS' makes this operation idempotent and safe to re-run.
        migrations.RunSQL(
            sql="ALTER TABLE core_machineproductdocument DROP COLUMN IF EXISTS external_url CASCADE;",
            state_operations=[
                migrations.RemoveField(
                    model_name='machineproductdocument',
                    name='external_url',
                ),
            ]
        ),
        # The 'overview_body' column may exist from a previous failed migration.
        # Using RunSQL with 'IF NOT EXISTS' makes this operation idempotent.
        migrations.RunSQL(
            sql="ALTER TABLE core_machineproduct ADD COLUMN IF NOT EXISTS overview_body text NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE core_machineproduct DROP COLUMN IF EXISTS overview_body;",
            state_operations=[
                migrations.AddField(
                    model_name='machineproduct',
                    name='overview_body',
                    field=models.TextField(blank=True, help_text='Main body text for the machine page'),
                ),
            ]
        ),
        # Proactively making this idempotent as well to prevent a similar error.
        migrations.RunSQL(
            sql="ALTER TABLE core_machineproduct ADD COLUMN IF NOT EXISTS overview_title varchar(140) NOT NULL DEFAULT 'Overview';",
            reverse_sql="ALTER TABLE core_machineproduct DROP COLUMN IF EXISTS overview_title;",
            state_operations=[
                migrations.AddField(
                    model_name='machineproduct',
                    name='overview_title',
                    field=models.CharField(blank=True, default='Overview', max_length=140),
                ),
            ]
        ),
        # Proactively making this idempotent as well.
        migrations.RunSQL(
            sql="ALTER TABLE core_machineproductdocument ADD COLUMN IF NOT EXISTS url varchar(200) NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE core_machineproductdocument DROP COLUMN IF EXISTS url;",
            state_operations=[
                migrations.AddField(
                    model_name='machineproductdocument',
                    name='url',
                    field=models.URLField(blank=True, help_text='Optional external link instead of uploading a file'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/hero/'),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='machineproduct',
            name='key_features',
            field=models.TextField(blank=True, help_text='One feature per line (we will display these as bullet points)'),
        ),
        # This AlterField operation fails because the unique constraint on 'slug'
        # already exists in the database. We replace it with a RunSQL no-op
        # that only applies the state change, allowing the migration to succeed.
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='machineproduct',
                    name='slug',
                    field=models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated if blank)', max_length=160, unique=True),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='machineproductdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='machines/documents/'),
        ),
        migrations.AlterField(
            model_name='machineproductdocument',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='machineproductimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='machineproductimage',
            name='image',
            field=models.ImageField(upload_to='machines/gallery/'),
        ),
        migrations.AlterField(
            model_name='machineproductvideo',
            name='embed_url',
            field=models.URLField(blank=True, default='', help_text='Optional: paste an embed URL (if blank we auto-generate from video_url where possible).'),
        ),
        migrations.AlterField(
            model_name='machineproductvideo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        # The video_url column is missing on the production DB.
        # This replaces the standard AlterField with an idempotent RunSQL operation
        # to ensure the column exists, while keeping Django's state consistent.
        migrations.RunSQL(
            sql="ALTER TABLE core_machineproductvideo ADD COLUMN IF NOT EXISTS video_url varchar(200) NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE core_machineproductvideo DROP COLUMN IF EXISTS video_url;",
            state_operations=[
                migrations.AlterField(
                    model_name='machineproductvideo',
                    name='video_url',
                    field=models.URLField(blank=True, default='', help_text='YouTube/Vimeo (watch link) or any external video URL'),
                ),
            ]
        ),
    ]
