# Generated by Django 5.0.1 on 2026-02-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_machineproductdocument_options_and_more'),
        ('core', '0058_railway_fix_missing_machineproduct_hero_cols'),
    ]

    operations = [
    ]
