# Generated by Django 5.0.1 on 2026-02-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_merge_20260215_2110'),
        ('core', '0_58_railway_fix_missing_machineproduct_hero_cols'),
    ]

    operations = [
    ]
