# Generated by ChatGPT on 2026-02-17

from django.db import migrations


def forwards_add_missing_video_columns(apps, schema_editor):
    """Railway/Postgres: some environments have the MachineProductVideo table but are missing
    the newer columns (video_url / embed_url). This migration adds them only if absent.

    This is intentionally defensive so it can run on:
    - Postgres (Railway)
    - SQLite (local dev)
    - Any DB supported by Django introspection
    """

    MachineProductVideo = apps.get_model("core", "MachineProductVideo")
    table = MachineProductVideo._meta.db_table
    conn = schema_editor.connection

    # If the table doesn't exist yet, do nothing (normal migrations will create it).
    try:
        existing_tables = set(conn.introspection.table_names())
    except Exception:
        existing_tables = set()

    if table not in existing_tables:
        return

    with conn.cursor() as cursor:
        try:
            cols = conn.introspection.get_table_description(cursor, table)
        except Exception:
            return

    existing_cols = {c.name for c in cols}

    # Add missing columns one-by-one (safe if only one is missing).
    for field_name in ("video_url", "embed_url"):
        if field_name in existing_cols:
            continue
        field = MachineProductVideo._meta.get_field(field_name)
        schema_editor.add_field(MachineProductVideo, field)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_merge_20260215_2141"),
    ]

    operations = [
        migrations.RunPython(forwards_add_missing_video_columns, migrations.RunPython.noop),
    ]
