# Generated by ChatGPT on 2026-02-21
from django.db import migrations


def _column_exists(cursor, table_name: str, column_name: str) -> bool:
    cursor.execute(
        '''
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        LIMIT 1
        ''',
        [table_name, column_name],
    )
    return cursor.fetchone() is not None


def _set_default_and_fill_nulls(cursor, table: str, column: str, default_sql: str = "''"):
    cursor.execute(f'UPDATE "{table}" SET "{column}" = {default_sql} WHERE "{column}" IS NULL;')
    cursor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{column}" SET DEFAULT {default_sql};')


def forwards(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor != "postgresql":
        return

    table = "core_machineproduct"
    with conn.cursor() as cursor:
        if _column_exists(cursor, table, "hero_heading"):
            _set_default_and_fill_nulls(cursor, table, "hero_heading", "''")
        if _column_exists(cursor, table, "hero_subheading"):
            _set_default_and_fill_nulls(cursor, table, "hero_subheading", "''")


def backwards(apps, schema_editor):
    # No-op (safe to keep defaults)
    return


class Migration(migrations.Migration):

    dependencies = [
        # IMPORTANT: Update this to your current latest core migration filename.
        # Example: ("core", "0061_previous_migration_name"),
        ("core", "0061_previous_migration_name"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
