# Generated by ChatGPT on 2026-02-15
# Purpose: Railway/Postgres DB is missing MachineProduct hero_title/hero_subtitle columns.
# This migration *only* patches the database (no state change), so it is safe even if your local DB already has the columns.

from django.db import migrations

def add_missing_columns(apps, schema_editor):
    vendor = schema_editor.connection.vendor

    # We only need to patch Postgres on Railway. Local dev (SQLite) typically already has the columns after a rebuild.
    if vendor != "postgresql":
        return

    # Add columns if they don't exist (Postgres supports IF NOT EXISTS)
    schema_editor.execute(
        "ALTER TABLE core_machineproduct ADD COLUMN IF NOT EXISTS hero_title varchar(200) NOT NULL DEFAULT '';"
    )
    schema_editor.execute(
        "ALTER TABLE core_machineproduct ADD COLUMN IF NOT EXISTS hero_subtitle varchar(300) NOT NULL DEFAULT '';"
    )
    # Add the missing video_url column to the video table.
    schema_editor.execute(
        "ALTER TABLE core_machineproductvideo ADD COLUMN IF NOT EXISTS video_url varchar(200) NOT NULL DEFAULT '';"
    )

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_machineproduct_stats_features"),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, migrations.RunPython.noop),
    ]
