from __future__ import annotations

from io import BytesIO
from typing import Optional

from django.utils import timezone


def generate_order_pdf_bytes(order, request=None) -> bytes:
    """Generate a simple Order Summary PDF (bytes) for attachment.

    If your project already has a richer PDF generator elsewhere, you can swap
    this implementation to call it, but this works in pure Python (ReportLab).
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas
        from reportlab.lib.units import mm
        from reportlab.lib import colors
    except ImportError:
        # ReportLab not available
        return b""

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    left = 20 * mm
    right = width - 20 * mm
    y = height - 25 * mm

    # Try to pull branding from PDFConfiguration (if present) or SiteConfiguration
    company_name = "MPE UK Ltd"
    header_email = "sales@mpe-uk.com"
    header_phone = "+44 1663 732700"
    header_location = "Derbyshire, UK"
    accent = "#2E7D32"
    title = "Order Summary"
    footer = "Generated by MPE Web Site"

    try:
        from core.models import PDFConfiguration  # type: ignore
        cfg = PDFConfiguration.get_config()
        company_name = getattr(cfg, "company_name", company_name) or company_name
        header_email = getattr(cfg, "header_email", header_email) or header_email
        header_phone = getattr(cfg, "header_phone", header_phone) or header_phone
        header_location = getattr(cfg, "header_location", header_location) or header_location
        accent = getattr(cfg, "accent_color", accent) or accent
        title = getattr(cfg, "document_title", title) or title
        footer = getattr(cfg, "footer_text", footer) or footer
        logo_field = getattr(cfg, "pdf_logo", None)
    except Exception:
        logo_field = None
        try:
            from core.models import SiteConfiguration
            sc = SiteConfiguration.get_config()
            company_name = "MPE UK Ltd"
            header_email = getattr(sc, "email", header_email) or header_email
            header_phone = getattr(sc, "phone_number", header_phone) or header_phone
            header_location = getattr(sc, "location", header_location) or header_location
        except Exception:
            pass

    # Logo (optional)
    try:
        import os
        from django.conf import settings
        if logo_field and getattr(logo_field, "name", None):
            # local path
            if hasattr(logo_field, "path"):
                logo_path = logo_field.path
            else:
                logo_path = None
        else:
            # fallback static logo if exists
            logo_path = os.path.join(settings.BASE_DIR, "static", "img", "mpe_logo.png")
            if not os.path.exists(logo_path):
                logo_path = None

        if logo_path:
            c.drawImage(logo_path, left, height - 35 * mm, width=45 * mm, preserveAspectRatio=True, mask="auto")
    except Exception:
        pass

    # Header text (top-right)
    c.setFont("Helvetica-Bold", 11)
    c.drawRightString(right, height - 18 * mm, company_name)
    c.setFont("Helvetica", 9)
    c.drawRightString(right, height - 24 * mm, header_email)
    c.drawRightString(right, height - 29 * mm, header_phone)
    c.drawRightString(right, height - 34 * mm, header_location)

    # Accent line
    try:
        c.setStrokeColor(colors.HexColor(accent))
    except Exception:
        c.setStrokeColor(colors.black)
    c.setLineWidth(1)
    c.line(left, height - 40 * mm, right, height - 40 * mm)

    # Title
    y = height - 55 * mm
    c.setFont("Helvetica-Bold", 16)
    c.drawString(left, y, title)

    # Meta
    created = getattr(order, "created_at", None) or getattr(order, "created", None) or timezone.now()
    status = getattr(order, "get_status_display", None)
    status_text = status() if callable(status) else getattr(order, "status", "")

    y -= 12 * mm
    c.setFont("Helvetica", 9)
    c.drawString(left, y, f"Order Ref: {getattr(order, 'id', '')}")
    c.drawString(left + 55 * mm, y, f"Status: {status_text}")
    c.drawString(left + 110 * mm, y, f"Created: {created:%d %b %Y %H:%M}")

    # Customer
    contact = getattr(order, "contact", None)
    cust_name = getattr(contact, "name", "") if contact else ""
    cust_company = getattr(contact, "company", "") if contact else ""
    cust_email = getattr(contact, "email", "") if contact else ""

    y -= 8 * mm
    c.drawString(left, y, f"Customer: {cust_name}")
    c.drawString(left + 55 * mm, y, f"Company: {cust_company}")
    c.drawString(left + 110 * mm, y, f"Email: {cust_email}")

    # Table header
    y -= 15 * mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left, y, "SKU")
    c.drawString(left + 30 * mm, y, "Item")
    c.drawRightString(left + 135 * mm, y, "Qty")
    c.drawRightString(left + 160 * mm, y, "Unit (£)")
    c.drawRightString(right, y, "Line (£)")
    c.setFont("Helvetica", 9)
    c.line(left, y - 2, right, y - 2)
    y -= 8

    total = 0.0
    items = getattr(order, "items", None)
    rows = items.all() if hasattr(items, "all") else []
    for it in rows:
        if y < 30 * mm:
            c.showPage()
            y = height - 30 * mm
            c.setFont("Helvetica", 9)

        sku = getattr(it, "sku", "") or getattr(it, "product_sku", "") or ""
        name = getattr(it, "product_name", "") or getattr(it, "name", "") or ""
        qty = getattr(it, "quantity", 0) or 0
        unit = float(getattr(it, "unit_price_gbp", 0) or getattr(it, "unit_price", 0) or 0)
        line = unit * float(qty)
        total += line

        c.drawString(left, y, str(sku))
        c.drawString(left + 30 * mm, y, str(name)[:55])
        c.drawRightString(left + 135 * mm, y, str(qty))
        c.drawRightString(left + 160 * mm, y, f"{unit:,.2f}")
        c.drawRightString(right, y, f"{line:,.2f}")
        y -= 6

    # Total
    y -= 5
    c.setFont("Helvetica-Bold", 11)
    c.drawRightString(right, y, f"Total: £{total:,.2f}")

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    c.drawCentredString(width / 2, 12 * mm, footer)

    c.showPage()
    c.save()
    return buf.getvalue()
