from __future__ import annotations

from io import BytesIO
from typing import Optional, Tuple
from urllib.request import urlopen

from django.utils import timezone


def _safe_hex_color(value: str, default: str = "#2E7D32") -> str:
    value = (value or "").strip()
    if not value:
        return default
    if not value.startswith("#"):
        value = "#" + value
    if len(value) not in (4, 7):
        return default
    # very small validation
    try:
        int(value[1:], 16)
        return value
    except Exception:
        return default


def _get_pdf_branding() -> Tuple[dict, Optional[object]]:
    """Return (branding_dict, logo_field). Never raises."""
    branding = {
        "company_name": "MPE UK Ltd",
        "header_email": "sales@mpe-uk.com",
        "header_phone": "+44 1663 732700",
        "header_location": "Derbyshire, UK",
        "accent_color": "#2E7D32",
        "document_title": "Order Summary",
        "footer_text": "Generated by MPE Web Site",
        "show_page_numbers": True,
    }
    logo_field = None

    try:
        from core.models import PDFConfiguration  # type: ignore
        cfg = PDFConfiguration.get_config()
        branding["company_name"] = getattr(cfg, "company_name", branding["company_name"]) or branding["company_name"]
        branding["header_email"] = getattr(cfg, "header_email", branding["header_email"]) or branding["header_email"]
        branding["header_phone"] = getattr(cfg, "header_phone", branding["header_phone"]) or branding["header_phone"]
        branding["header_location"] = getattr(cfg, "header_location", branding["header_location"]) or branding["header_location"]
        branding["accent_color"] = _safe_hex_color(getattr(cfg, "accent_color", branding["accent_color"]) or branding["accent_color"])
        branding["document_title"] = getattr(cfg, "document_title", branding["document_title"]) or branding["document_title"]
        branding["footer_text"] = getattr(cfg, "footer_text", branding["footer_text"]) or branding["footer_text"]
        branding["show_page_numbers"] = bool(getattr(cfg, "show_page_numbers", True))
        logo_field = getattr(cfg, "pdf_logo", None)
        return branding, logo_field
    except Exception:
        pass

    # Fallback to SiteConfiguration if present
    try:
        from core.models import SiteConfiguration  # type: ignore
        sc = SiteConfiguration.get_config()
        branding["company_name"] = getattr(sc, "company_name", branding["company_name"]) or branding["company_name"]
        branding["header_email"] = getattr(sc, "email", branding["header_email"]) or branding["header_email"]
        branding["header_phone"] = getattr(sc, "phone_number", branding["header_phone"]) or branding["header_phone"]
        branding["header_location"] = getattr(sc, "location", branding["header_location"]) or branding["header_location"]
    except Exception:
        pass

    return branding, logo_field


def _load_logo_as_imagereader(logo_field) -> Optional[object]:
    """Return a ReportLab ImageReader for the configured logo (local or remote)."""
    try:
        from reportlab.lib.utils import ImageReader
    except Exception:
        return None

    if not logo_field or not getattr(logo_field, "name", None):
        return None

    # 1) Local storage path (works in dev, and if MEDIA is local)
    try:
        if hasattr(logo_field, "path"):
            return ImageReader(logo_field.path)
    except Exception:
        pass

    # 2) Remote URL (Cloudinary / S3 / etc.)
    try:
        url = getattr(logo_field, "url", None)
        if url:
            with urlopen(url) as resp:
                data = resp.read()
            return ImageReader(BytesIO(data))
    except Exception:
        return None

    return None


def generate_order_pdf_bytes(order, request=None) -> bytes:
    """Generate a branded Order Summary PDF (bytes) for download + email attachment.

    This implementation is *pure ReportLab* (no WeasyPrint dependency), and supports:
      - PDFConfiguration branding fields from Django admin
      - Cloudinary/remote logos (fetched via logo_field.url)
      - Clean, professional header + table layout

    It never raises; returns b"" on failure.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas
        from reportlab.lib.units import mm
        from reportlab.lib import colors
        from reportlab.platypus import Table, TableStyle
    except Exception:
        return b""  # ReportLab not installed

    branding, logo_field = _get_pdf_branding()
    accent = branding.get("accent_color", "#2E7D32")
    accent = _safe_hex_color(accent)

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    left = 18 * mm
    right = width - 18 * mm
    top = height - 18 * mm
    y = top

    # --- Header: Logo (left) + Company block (right)
    logo = _load_logo_as_imagereader(logo_field)

    header_height = 24 * mm
    if logo:
        try:
            c.drawImage(logo, left, top - header_height, width=46 * mm, height=header_height, preserveAspectRatio=True, mask="auto")
        except Exception:
            pass

    c.setFont("Helvetica-Bold", 12)
    c.drawRightString(right, top - 2 * mm, str(branding.get("company_name", ""))[:120])

    c.setFont("Helvetica", 9)
    c.drawRightString(right, top - 8 * mm, str(branding.get("header_email", ""))[:120])
    c.drawRightString(right, top - 13 * mm, str(branding.get("header_phone", ""))[:120])
    c.drawRightString(right, top - 18 * mm, str(branding.get("header_location", ""))[:120])

    # Accent line under header
    try:
        c.setStrokeColor(colors.HexColor(accent))
    except Exception:
        c.setStrokeColor(colors.green)
    c.setLineWidth(2)
    c.line(left, top - 26 * mm, right, top - 26 * mm)

    y = top - 34 * mm

    # --- Title + meta
    c.setFont("Helvetica-Bold", 14)
    c.drawString(left, y, str(branding.get("document_title", "Order Summary"))[:120])
    y -= 7 * mm

    c.setFont("Helvetica", 9)
    order_id = getattr(order, "id", "")
    created_at = getattr(order, "created_at", None) or timezone.now()
    created_str = created_at.strftime("%d %b %Y %H:%M")
    c.drawString(left, y, f"Order #: {order_id}")
    c.drawRightString(right, y, f"Date: {created_str}")
    y -= 8 * mm

    # --- Customer / delivery summary (best-effort)
    def _safe(getter, default=""):
        try:
            v = getter()
            return "" if v is None else str(v)
        except Exception:
            return default

    contact = getattr(order, "contact", None)
    customer_name = _safe(lambda: getattr(contact, "name", "")) if contact else ""
    customer_company = _safe(lambda: getattr(contact, "company", "")) if contact else ""
    customer_email = _safe(lambda: getattr(contact, "email", "")) if contact else ""
    customer_phone = _safe(lambda: getattr(contact, "phone_number", "")) if contact else ""

    lines = []
    if customer_company:
        lines.append(customer_company)
    if customer_name:
        lines.append(customer_name)
    if customer_email:
        lines.append(customer_email)
    if customer_phone:
        lines.append(customer_phone)

    if lines:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(left, y, "Customer")
        y -= 5 * mm
        c.setFont("Helvetica", 9)
        for ln in lines[:4]:
            c.drawString(left, y, ln[:120])
            y -= 4.5 * mm
        y -= 2 * mm

    # --- Items table
    items_qs = getattr(order, "items", None)
    try:
        items = list(items_qs.all()) if items_qs is not None else []
    except Exception:
        items = []

    table_data = [["Item", "Qty"]] if not show_prices else [["Item", "Qty", "Price", "Line Total"]]

    currency = "£"
    total = 0.0

    for it in items:
        name = str(getattr(it, "product_name", "") or getattr(getattr(it, "product", None), "name", "") or "Item")[:80]
        qty = float(getattr(it, "quantity", 1) or 1)
# Order items store unit price in unit_price_gbp. 'line_total' may be a method.
price = float(getattr(it, "unit_price_gbp", 0) or getattr(it, "unit_price", 0) or getattr(it, "price", 0) or 0)
computed_line_total = qty * price

lt = getattr(it, "line_total", None)
try:
    lt_val = lt() if callable(lt) else lt
except Exception:
    lt_val = None

line_total_value = float(getattr(it, "line_total_gbp", 0) or (lt_val or computed_line_total))

if show_prices and price:
    total += line_total_value
if not show_prices:
    table_data.append([name, f"{qty:g}"])
else:
    price_display = f"{currency}{price:,.2f}" if price else "On request"
    line_display = f"{currency}{line_total_value:,.2f}" if price else "—"
    table_data.append([name, f"{qty:g}", price_display, line_display])

    # If no items, still show a placeholder row
    if len(table_data) == 1:
        table_data.append(["(No items)", "", "", ""])

    # Build table
    col_widths = [110 * mm, 18 * mm, 25 * mm, 27 * mm]
    tbl = Table(table_data, colWidths=col_widths)

    header_bg = colors.HexColor(accent) if accent else colors.lightgrey
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_bg),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey]),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))

    table_w, table_h = tbl.wrapOn(c, right - left, y - 30 * mm)
    if y - table_h < 25 * mm:
        c.showPage()
        y = height - 30 * mm

    tbl.drawOn(c, left, y - table_h)
    y = y - table_h - 8 * mm

    # --- Totals
    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(right, y, f"Total: {currency}{total:,.2f}")
    y -= 10 * mm

    # --- Footer
    c.setFont("Helvetica", 8)
    footer = str(branding.get("footer_text", ""))[:160]
    c.setFillColor(colors.grey)
    c.drawString(left, 12 * mm, footer)
    c.setFillColor(colors.black)

    # Page numbers (best-effort; single-page numbering here)
    if bool(branding.get("show_page_numbers", True)):
        c.setFont("Helvetica", 8)
        c.drawRightString(right, 12 * mm, "Page 1")

    c.showPage()
    c.save()
    pdf = buf.getvalue()
    buf.close()
    return pdf
