"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.1.
"""

from pathlib import Path
import os
import dj_database_url

# -----------------------------------------------------------------------------
# Base paths
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# Marketing / Tracking (optional)
# -----------------------------------------------------------------------------
# Lead Forensics tracking script (loaded only after cookie consent)
LEAD_FORENSICS_ENABLED = os.getenv("LEAD_FORENSICS_ENABLED", "True").lower() == "true"
LEAD_FORENSICS_SCRIPT_SRC = os.getenv(
    "LEAD_FORENSICS_SCRIPT_SRC",
    "https://secure.informationcreativeinnovative.com/js/102273.js",
)

# -----------------------------------------------------------------------------
# SECURITY
# -----------------------------------------------------------------------------

# SECRET KEY
# - Local: uses fallback
# - Railway: MUST be set in Variables
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "dev-only-unsafe-secret-key-change-me"
)

# DEBUG
# - Local default: True
# - Railway: set DEBUG=False
DEBUG = os.getenv("DJANGO_DEBUG", os.getenv("DEBUG", "True")).lower() == "true"

# ALLOWED HOSTS
# - Local default: 127.0.0.1,localhost
# - Railway: include *.railway.app by default
#
# We parse the environment variable, but we ALSO explicitly add your
# custom domains below to ensure they always work.
_allowed_hosts_raw = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost"),
)

ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(",") if h.strip()]

# ALWAYS add your custom domains and Railway defaults
ALLOWED_HOSTS.extend([
    "www.mpe-uk.com",
    "mpe-uk.com",
    ".railway.app",
    ".up.railway.app"
])

# De-duplicate while preserving order
_seen = set()
ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if not (h in _seen or _seen.add(h))]


# CSRF (required for HTTPS on Railway)
# This is crucial for forms (like Admin login) to work on your new domain.
_csrf_env = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", os.getenv("CSRF_TRUSTED_ORIGINS", "")).strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(",") if o.strip()]

# Always extend with your trusted domains
CSRF_TRUSTED_ORIGINS.extend([
    "https://*.up.railway.app",
    "https://*.railway.app",
    "https://www.mpe-uk.com",
    "https://mpe-uk.com",
])

# -----------------------------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Optional media backend (Cloudinary) – enabled only when env vars are present.
    # We leave the apps installed so imports/migrations stay consistent.
    "cloudinary_storage",
    "cloudinary",
    'import_export',
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_config",  # Site configuration
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"

# -----------------------------------------------------------------------------
# DATABASE
# -----------------------------------------------------------------------------

# Railway: DATABASE_URL (Postgres)
# Local fallback: SQLite
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# -----------------------------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------------------------------------------
# INTERNATIONALISATION
# -----------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# STATIC FILES (WhiteNoise)
# -----------------------------------------------------------------------------

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# If you run behind a proxy (Railway), this ensures Django sees HTTPS correctly
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# WhiteNoise: prevent hard 500s if a referenced static asset is missing from the manifest
# (You should still fix missing assets, but this stops production from going down.)
WHITENOISE_MANIFEST_STRICT = os.getenv("WHITENOISE_MANIFEST_STRICT", "False").lower() == "true"

# -----------------------------------------------------------------------------
# MEDIA FILES (Admin uploads: images, PDFs)
# -----------------------------------------------------------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))

# -----------------------------------------------------------------------------
# DEFAULTS
# -----------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# -----------------------------------------------------------------------------
# MEDIA STORAGE BACKEND
# -----------------------------------------------------------------------------
#
# This project is intended to deploy on Railway.com.
#
# - On Railway: set the Cloudinary variables so uploads (ImageField/FileField) are stored
#   off-disk (Railway containers have ephemeral filesystems).
# - Locally: if you *don't* set Cloudinary vars, we fall back to local MEDIA_ROOT so the
#   site runs without extra setup.

_cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME", "").strip()
_api_key = os.getenv("CLOUDINARY_API_KEY", "").strip()
_api_secret = os.getenv("CLOUDINARY_API_SECRET", "").strip()

USE_CLOUDINARY = bool(_cloud_name and _api_key and _api_secret)

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": _cloud_name,
        "API_KEY": _api_key,
        "API_SECRET": _api_secret,
    }
    # Use Cloudinary for any file uploaded to a FileField/ImageField
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
else:
    # Default Django FileSystemStorage (uses MEDIA_ROOT/MEDIA_URL)
    # IMPORTANT: On Railway this will *not* persist, so ensure you set the Cloudinary vars.
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"


# -----------------------------------------------------------------------------
# Email (SMTP) - e.g. Brevo
# -----------------------------------------------------------------------------
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587")) if os.getenv("EMAIL_PORT") else 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes", "on")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in ("1", "true", "yes", "on")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", os.getenv("EMAIL_FROM", "sales@mpe-uk.com"))

# Token used by the /diag/email/ endpoint (leave blank to disable)
EMAIL_DIAG_TOKEN = os.getenv("EMAIL_DIAG_TOKEN", "").strip()